### ISSUE TITLE
RobotFramework-Examples no more working with RF 6.1

### ISSUE THREAD

**Issue by orenault** [worldline/RobotFramework-Examples#2]
Hi,

RobotFramework-Examples is not working anymore with the latest RF release (6.1).

Error message is:
[ ERROR ] Calling method '_start_suite' of listener 'Examples' failed: AttributeError: 'Keyword' object has no attribute 'tags'

**Comment by orenault** [comment]
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-6.1.rst#changes-to-testsuite-model-structure

...
Another related change is that doc, tags, timeout and teardown attributes were removed from the [robot.running.Keyword](https://robot-framework.readthedocs.io/en/latest/autodoc/robot.running.html#robot.running.model.Keyword) object (https://github.com/robotframework/robotframework/issues/4589). They were left there accidentally and were not used for anything by Robot Framework. Tools accessing them need to be updated.
...

**Comment by VernonCrabtree** [comment]
I have made tags and timeout at keyword level optional.
Seems to work now, but needs testing (apart from the tests in the build pipeline)
